### ISSUE TITLE
soda application token

### ISSUE THREAD

**Issue by thfield** [sfbrigade/datasci-SF-Environment-Benchmark#14]
we should probably sign up for an [application token](https://dev.socrata.com/foundry/data.sfgov.org/75rg-imyz)

**Comment by eayoungs** [comment]
I've created a token in my [account](https://data.sfgov.org/profile/eayoungs/dewc-yk3e/app_tokens). Not sure if we have a project account @ `data.sfgov.org` or not. Let me know if we should create one.

**Comment by eayoungs** [comment]
Instructions are here: https://dev.socrata.com/docs/app-tokens.html
I will post the public token in the Slack channel.
There is a "Secret Token" but it doesn't seem to be used anywhere. Seems like the public token is just a way to keep track of who's using how much bandwidth.
