### ISSUE TITLE
Create new HTML for custom dashboard page

### ISSUE THREAD

**Issue by askiefer** [sfbrigade/datasci-SF-Environment-Benchmark#19]
Create new HTML page for the building-specific dashboard page (still in progress, latest mockups [here](https://projects.invisionapp.com/share/2SAI4AK48#/219556065_SF-Environment-Benchmark)). For the summary statistics, add stub figure XXX. 

Note: this shouldn't be started until the mock ups are finalized and reviewed by SF Dept of Env

Some HTML from the existing dashboard page can likely be used / refactored (file [here](datasci-SF-Environment-Benchmark/dashboard/index.html)). 

The new charts / graphs to be created will be in a separate issue. 

cc @thfield @eayoungs @smoningi

**Comment by thfield** [comment]
we can probably close this?  seems to be addressed in #25 and #29

**Comment by askiefer** [comment]
yup, closing!
