### ISSUE TITLE
Add function for custom building urls

### ISSUE THREAD

**Issue by askiefer** [sfbrigade/datasci-SF-Environment-Benchmark#20]
- Add a function to provide URL params for parcel ID, to uniquely identify building visualizations by Parcel IDs in URL (ex ... /dashboard/office/parcel_id#) 

cc @smoningi @eayoungs @thfield feel free to beef this up

**Comment by thfield** [comment]
I got this as an email notification and thought it was a PR, I was excited thinking that you had already done this 🙂

**Comment by eayoungs** [comment]
Not yet, but I'll be looking into it soon!

**Comment by eayoungs** [comment]
@thfield Looks like there is a reference to the parameter in question in `individual/individual.js ln13` (master branch)

**Comment by eayoungs** [comment]
This query seems to work:
`https://data.sfgov.org/resource/75rg-imyz.json?$where=parcel_s=='0267/009'`

**Comment by askiefer** [comment]
Ah apologies to disappoint @thfield. Awesome @eayoungs!

**Comment by thfield** [comment]
@eayoungs yup, [this line](https://github.com/sfbrigade/datasci-SF-Environment-Benchmark/blob/master/individual/individual.js#L21) illustrates a little better how I was thinking the flow would work..  I'm imagining the page URL, something like `http://our-sweet-viz-app/?parcel="0267/009"` , gets read by our script, then uses `propertyQuery()` to get that property's specific details, which then call `propertyQuery()` again to find details on other similar parcels

**Comment by eayoungs** [comment]
Should I close this issue, then?

**Comment by thfield** [comment]
not yet, since nobody has actually written the code to do this yet

**Comment by eayoungs** [comment]
Ah, of course!

**Comment by thfield** [comment]
@techieshark fixed this in #38
