### ISSUE TITLE
Add Z-Score for individual buildings

### ISSUE THREAD

**Issue by eayoungs** [sfbrigade/datasci-SF-Environment-Benchmark#26]
In my first attempt at adding Z-scores I assumed that the easiest way to incorporate the additional information while preserving the data structure was to read the JSON file into a dataframe, process the dataframe, add a column with the results and write back to a new JSON file with the new data appended but it turns out the structure of the JSON file is presenting challenges.
My next thoughts are to either dig deeper into the structure and try to work with it or create some third data-structure, like a database schema. Neither sound appealing at the moment so I wonder if anyone else has a suggestion or can at least tell me if I'm crazy or not?

Thanks-in-advance!

Eric

**Comment by eayoungs** [comment]
Right now I'm attempting to use this Pandas function but I'm running into `KeyError`. http://pandas.pydata.org/pandas-docs/stable/generated/pandas.io.json.json_normalize.html

**Comment by smoningi** [comment]
I think we should calculate the Z-scores on the fly in javascript. This
will allow us to adapt to new datasets being added every year from the API.
If it does seem like too much overhead, then we can do it as a
preprocessing step.

**Comment by eayoungs** [comment]
Sounds fine by me. I'm not familiar enough with JavaScript to know how much overhead it will introduce but it doesn't seem like an intense calculation and the dataset is relatively static.

**Comment by thfield** [comment]
there is [a point](https://github.com/thfield/SF-Environment-Benchmark/blob/master/dashboard/dashboard.js#L279) in my response handler where the data that's been returned from soda-js has been super simplified and might be exactly what you're looking for.  with a breakpoint at L281, running `console.log(JSON.stringify(categoryData))` should get a json string you can work with in python

i agree with sanat that this should be calculated on-the-fly and i'd be happy to help with translating into JS. [this step](https://github.com/thfield/SF-Environment-Benchmark/blob/master/dashboard/dashboard.js#L433) is a placeholder for that calculation.
