### ISSUE TITLE
Increase width of bars in histogram and add line and site text

### ISSUE THREAD

**Issue by askiefer** [sfbrigade/datasci-SF-Environment-Benchmark#55]
Ammon requested that we make the bar charts look more like the mockup - specifically, increase the width of the bars in the two histograms, add the dashed line (it's solid now) indicating where the specific building lies on the histogram and add a label for the specific building as in the mockup.

<img width="459" alt="screen shot 2017-07-11 at 9 51 45 pm" src="https://user-images.githubusercontent.com/13832695/28102304-32d6ccac-6683-11e7-8b68-df18fcdc73ae.png">

@thfield You did such a good job with the radial chart that I'm assigning this to you - lmk if you can't take it on for some reason and I can look into it

cc @eayoungs

**Comment by thfield** [comment]
One thing about with making the bars wider: they are spaced to be roughly 1/100th of the width of the chart.  Possible solutions:
- make the chart wider
- bin the data at more than 1/bin

**Comment by thfield** [comment]
other possible solution: change x-axis [min, max] to be the min/max of the data instead of 0,100

**Comment by thfield** [comment]
related to #82, close this when we hear back about the ideal binning

**Comment by thfield** [comment]
from DOE email: use bin of 20
