### ISSUE TITLE
Make site mobile responsive

### ISSUE THREAD

**Issue by askiefer** [sfbrigade/datasci-SF-Environment-Benchmark#56]
Make each page mobile responsive according to the mockup here: https://projects.invisionapp.com/d/main#/console/10323668/241362220/preview

@eayoungs I would love the help on this if you have bandwidth but I'll assign myself primarily. It should be easier with the removal of the three tabs.

**Comment by eayoungs** [comment]
Hey, I hate to be a whiner but I don't have access to the mockup. >.<

**Comment by eayoungs** [comment]
So, the site seems to scale but the words get cut off; I'm not exactly sure how to address this but I think we need to decide how to deal with the side-bar. I think it would alleviate some of the space issues to move the sidebar to a vertical position (mobile detection).

PS: Looks like we still using bootstrap?

**Comment by eayoungs** [comment]
Looks great! I guess we were thinking alike; just 'inline' the sidebar and put it at the top.

**Comment by thfield** [comment]
I don't have access to the mockup: Does #102 implement the design enough to close this?

**Comment by thfield** [comment]
sounds like #102 fixes this issue, closing
