### ISSUE TITLE
Add a Benchmark Compliance status to side panel

### ISSUE THREAD

**Issue by askiefer** [sfbrigade/datasci-SF-Environment-Benchmark#57]
Ammon requested that we add a "2016 Benchmark Compliance" of the specific building on the side panel under the building's information (under floor area). I've added a bit of the html for this but still need some javascript written to replace the element ID with either a red ``X`` or a green checkmark (I'll likely use a font awesome checkmark ``<i class="fa fa-check" aria-hidden="true"></i>``) based on the building's current compliance status which should come from the data and is updated

**Comment by thfield** [comment]
mostly there in `57-feature-current-year-compliance`: just needs css to make the x red

**Comment by eayoungs** [comment]
All the formatting looked good to me but I noticed that the status was wrong for 2016; looks like the code to find the 'latest' year was abandoned.
I hacked it to work in PR#73, which will work for the current compliance reports but doesn't fully resolve this issue.

**Comment by thfield** [comment]
closing, as fixed in #62.  we should change the x and checkmark to "complied/did not comply" as per request in another PR
