### ISSUE TITLE
benchmark compliance status not reporting correctly

### ISSUE THREAD

**Issue by thfield** [sfbrigade/datasci-SF-Environment-Benchmark#74]
variable `latest_benchmark_status` is not being correctly scraped from soda-returned data in function `latest()` see code [here](https://github.com/sfbrigade/datasci-SF-Environment-Benchmark/blob/master/dashboard/dashboard.js#L393)  (probably starting in L404)

**Comment by eayoungs** [comment]
A temporary fix is issued in PR79 that gives us a full year.
This will require revising the `latest()` function and might be best accomplished along with refactoring **dashboard.js** (_relates to issue 63_).

**Comment by thfield** [comment]
i believe this is fixed incidentally with #89 [here](https://github.com/sfbrigade/datasci-SF-Environment-Benchmark/pull/89/files#diff-5e5c014df471d720d257c5fd4368034fR417)

**Comment by thfield** [comment]
closing as fixed
