### ISSUE TITLE
switch to css grid layout

### ISSUE THREAD

**Issue by thfield** [sfbrigade/datasci-SF-Environment-Benchmark#76]
use [css grids](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout) for layout instead of bootstrap to get ready for mobile layout

**Comment by eayoungs** [comment]
This looks like what we want to acheive.
https://hacks.mozilla.org/2017/04/replace-bootstrap-layouts-with-css-grid/

**Comment by thfield** [comment]
closing; will not implement
