### ISSUE TITLE
Local ranking: high number for better score

### ISSUE THREAD

**Issue by eayoungs** [sfbrigade/datasci-SF-Environment-Benchmark#78]
We agreed that the local ranking score should conform to the high-is-better format of the Energy Star score. This reduces cognitive overhead and increases internal consistency in the data presentation.

**Comment by eayoungs** [comment]
This should probably be _verified_ with the **SF Dept. of Environment** before implementing.

**Comment by thfield** [comment]
related to #72?

**Comment by thfield** [comment]
in meeting with dept of env today, we discussed removing the ring chart and instead displaying something like: 
```
#1
ranked #1 out of 23 Office buildings sized 10,000 - 25,000 sqf in San Francisco
```

**Comment by thfield** [comment]
i noticed that the ranking function in use right now (`rankBuildings()`) is overly simple, and only ranks according to one metric.  wasn't there a system of ranking that we were going to implement?  there are comments indicating as much.

relates to #73, #72, and #81

**Comment by askiefer** [comment]
@thfield I thought Ammon had instructed us to use EStar Score as the ranking, followed by Site EUI only when there was a tie in the EStar Score. @eayoungs can you confirm (I think you worked on this part?)

**Comment by thfield** [comment]
That sounds familiar to me, we must have just never implemented it that way...

**Comment by thfield** [comment]
it looks like I overwrote some work on the ranking function while merging today.  I'll see about fixing it
