### ISSUE TITLE
Update the data to include 2015 commercial performance data 

### ISSUE THREAD

**Issue by askiefer** [sfbrigade/datasci-SF-Environment-Benchmark#9]
- [x] Investigate the 2015 dataset - https://data.sfgov.org/Energy-and-Environment/Existing-Commercial-Buildings-Energy-Performance-O/j2j3-acqj
- [ ] The 2013 dataset has data for 470 buildings, while the 2016 dataset has includes data for 1672 buildings. Why the significant increase? Were more buildings required to report in 2015 v 2013? Are we sure the 2013 data is complete?
- [x] Update the project to include the 2015 data
- [ ] Could offer the potential for showing year-by-year data differences

Code that reads in the data is in [JustGeo.js](https://github.com/sfbrigade/datasci-SF-Environment-Benchmark/blob/master/js/justGeo.js)

**Comment by judecalvillo** [comment]
Given the tasking mode of this repo's issues, you guys should totally try out the 'Projects' tab in your repo (relatively new GH feature). Essentially, you can group notes in a Kanban view (like Trello) and then convert them into issues. It's just a nice way to organize issues and notes. -- Anyways, just a suggestion. Glad to see you guys delving deeper into this project!

**Comment by eayoungs** [comment]
Data is ingested at this line in _dashboard.js_ 
                                                          `https://data.sfgov.org/resource/j2j3-acqj.json?$limit=2000`
New Socrata API endpoint: "https://data.sfgov.org/resource/75rg-imyz.json"

**Comment by eayoungs** [comment]
Data-set documentation lives here: https://dev.socrata.com/foundry/data.sfgov.org/75rg-imyz

**Comment by eayoungs** [comment]
I got it working separately but not in the main D3.js file: https://github.com/eayoungs/datasci-SF-Environment-Benchmark/blob/eayoungs/test.js

It runs at the terminal with Node v6.3.1; it looks, to me, like there is some sort of import issue with the modules.

I’m trying it with the dashboard.js file; https://github.com/eayoungs/datasci-SF-Environment-Benchmark/blob/eayoungs/dashboard/dashboard.js
lines: `72 - 74` & `78 - 87` ^

Apologies for the formatting & syntax; I’m new to JavaScript. ¯\_(ツ)_/¯
Also, _dashborad.js_ runs fine with the the output of _test.js_ saved to a .JSON file.
Ultimately I’d like to avoid saving to a file, this is just for troubleshooting.

**Comment by thfield** [comment]
Did we ever figure out what the difference was between 75rg-imyz and j2j3-acqj?

**Comment by thfield** [comment]
(it appears the difference is 75rg-imyz returns json object keys sorted, while j2j3-acqj returns them in some non-order)

**Comment by eayoungs** [comment]
I received this from @jasonlally via Regan Ammon:

If you want I can follow up with Eric. This is a Socrata thing. There are 2 ids for every dataset. One for the old API and one for the new API. **He should use the one from the new API on the dataset documentation 75rg-imyz (API v2.1)**
 
Socrata replicates the data from the original source. The documentation page has a sidebar labeled “Synchronized Copy” that shows when it was synced with the original.
 
Jason

**Comment by eayoungs** [comment]
@thfield Looks like this issue might be covered by PR #13 
(`individual/individual.js ln36~46`)

**Comment by eayoungs** [comment]
Did you guys ever get an answer about the difference between the "2013" vs. "2016" data (second check-point in the initial comment). I'm not sure that those dates actually correspond to actual data-sets, since we've been looking at **2015** but just wanted to check in for completeness.
I was going to open a new _Project_ as @judecalvillo mentioned but doesn't seem like a high priority if it's just for the last check-point. Seems like a low-priority feature.

**Comment by thfield** [comment]
Not sure we asked that question, but Anna might know better than I.  It seems like the "YYYY dataset" refers to the year of collecting

**Comment by thfield** [comment]
closing as we're using `soda-js` to grab directly from socrata
